algoritmo "semnome"
// Função :
// Autor :
// Data : 08/04/2025
// Seção de Declarações
var
contador, numero, maior, menor:inteiro
f:literal
inicio


escreva ("Informe o numero: ")
leia(numero)
enquanto numero <> 0 faca
se numero > maior entao
maior <- numero
fimse
enquanto numero <> 0 faca
se numero < maior entao
menor <- numero
fimse

fimenquanto



escreval("O maior numero digitado foi: ", maior)
escreval("O menor numero digitado foi: ", menor)


fimalgoritmo
