algoritmo "semnome"
// Função :
// Autor :
// Data : 08/04/2025
// Seção de Declarações 
var
contador, numero, maior:inteiro
f:literal
inicio


escreva ("Informe o numero: ")
leia(numero)
enquanto numero <> 0 faca
se numero > maior entao
maior <- numero
fimse

escreva ("Informe o numero: ")
leia(numero)
fimenquanto

escreval("O maior numero digitado foi: ", maior )




fimalgoritmo
